import { defineConfig } from "oxfmt";
import ultracite from "ultracite/oxfmt";

export default defineConfig({
  ...ultracite,
  // Generated by `buf generate`; its shape is protoc-gen-es's, not ours.
  ignorePatterns: [...(ultracite.ignorePatterns ?? []), "packages/proto/gen/**", "apps/ios/**"],
});
