/**
 * computer.v1 wire: generated by `buf generate` from api/computer.proto.
 * Method paths come from the generated service descriptors: do not hardcode.
 */
import { Agent, Seat } from "../gen/es/computer_pb.ts";

export { Agent, Seat } from "../gen/es/computer_pb.ts";

function path(service: { typeName: string }, method: { name: string }): string {
  return `/${service.typeName}/${method.name}`;
}

export const AgentMethods = {
  Computer: path(Agent, Agent.method.computer),
  Identity: path(Agent, Agent.method.identity),
  ReadFile: path(Agent, Agent.method.readFile),
  SendMessage: path(Agent, Agent.method.sendMessage),
  Shell: path(Agent, Agent.method.shell),
  Spec: path(Agent, Agent.method.spec),
  WriteFile: path(Agent, Agent.method.writeFile),
} as const;

export const SeatMethods = {
  ApplyBotTemplate: path(Seat, Seat.method.applyBotTemplate),
  ClipboardGet: path(Seat, Seat.method.clipboardGet),
  ClipboardSet: path(Seat, Seat.method.clipboardSet),
  Conversations: path(Seat, Seat.method.conversations),
  CreateBot: path(Seat, Seat.method.createBot),
  DeleteBot: path(Seat, Seat.method.deleteBot),
  ExportBotTemplate: path(Seat, Seat.method.exportBotTemplate),
  Occurrences: path(Seat, Seat.method.occurrences),
  Pair: path(Seat, Seat.method.pair),
  Pointer: path(Seat, Seat.method.pointer),
  ProvideSecret: path(Seat, Seat.method.provideSecret),
  RefreshCodingSession: path(Seat, Seat.method.refreshCodingSession),
  SetBotProfile: path(Seat, Seat.method.setBotProfile),
  SetPresence: path(Seat, Seat.method.setPresence),
  StartCodingSession: path(Seat, Seat.method.startCodingSession),
  Revoke: path(Seat, Seat.method.revoke),
  Issue: path(Seat, Seat.method.issue),
  Status: path(Seat, Seat.method.status),
  Type: path(Seat, Seat.method.type),
  WhatsAppAccounts: path(Seat, Seat.method.whatsAppAccounts),
  WhatsAppConfig: path(Seat, Seat.method.whatsAppConfig),
  WhatsAppGroups: path(Seat, Seat.method.whatsAppGroups),
  WhatsAppJoinGroup: path(Seat, Seat.method.whatsAppJoinGroup),
  WhatsAppLink: path(Seat, Seat.method.whatsAppLink),
} as const;

export const ALL_METHODS = [
  ...Agent.methods.map((m) => path(Agent, m)),
  ...Seat.methods.map((m) => path(Seat, m)),
] as const;

export type AuthPolicy = "public" | "pair" | "agent" | "seat";
