/**
 * computer.v1 wire: generated by `buf generate` from api/computer.proto.
 * Method paths come from the generated service descriptors — do not hardcode.
 */
export { Agent, Seat } from "../gen/es/computer_pb.ts";
export * as pb from "../gen/es/computer_pb.ts";

export {
  DISPLAY,
  WORKSPACE,
  SPEC_ID,
  SPEC_VERSION,
  TOOLS,
  type SeatState,
  type ErrorCode,
  type Action,
  type ActionResult,
  type PendingCheck,
  type BoxStatus,
  type Button,
  type Point,
  type RequestId,
} from "@computer/shared";

import { Agent, Seat } from "../gen/es/computer_pb.ts";

export const PACKAGE = "computer.v1" as const;

function path(service: { typeName: string }, method: { name: string }): string {
  return `/${service.typeName}/${method.name}`;
}

export const AgentMethods = {
  Spec: path(Agent, Agent.method.spec),
  SendMessage: path(Agent, Agent.method.sendMessage),
  Computer: path(Agent, Agent.method.computer),
  Shell: path(Agent, Agent.method.shell),
  ReadFile: path(Agent, Agent.method.readFile),
  WriteFile: path(Agent, Agent.method.writeFile),
} as const;

export const SeatMethods = {
  Pair: path(Seat, Seat.method.pair),
  Status: path(Seat, Seat.method.status),
  SetPresence: path(Seat, Seat.method.setPresence),
  Pointer: path(Seat, Seat.method.pointer),
  Type: path(Seat, Seat.method.type),
  ClipboardGet: path(Seat, Seat.method.clipboardGet),
  ClipboardSet: path(Seat, Seat.method.clipboardSet),
  Occurrences: path(Seat, Seat.method.occurrences),
  ProvideSecret: path(Seat, Seat.method.provideSecret),
  CreateBot: path(Seat, Seat.method.createBot),
  DeleteBot: path(Seat, Seat.method.deleteBot),
} as const;

export const ALL_METHODS = [
  ...Agent.methods.map((m) => path(Agent, m)),
  ...Seat.methods.map((m) => path(Seat, m)),
] as const;

export type AuthPolicy = "public" | "pair" | "agent" | "seat";
